### ISSUE TITLE
Effects are lost after merging layers

### ISSUE THREAD

**Issue by robertweglarek** [kmike/psd-tools#48]
When `.as_PIL()` is ran on a layer all effects are gone (like opacity etx...)
However, when `.as_PIL()` is run on the whole PSD - those effects are there.

Is there any way to fix it for layers' `.as_PIL()`?

**Comment by EvgenKo423** [comment]
Hi, @robertweglarek.

Layer effects are actually not a part of a layer, they are modifiers. So when you run `.as_PIL()` on a layer it returns an image of this layer (however opacity should be there).
When you run `.as_PIL()` on a whole PSD it returns a composite image, pre-rendered by Photoshop. That's why the effects are there.

Currently there is an experimental feature for merging layers, but it produces the precise result only in simple cases - alpha transparency is supported, but nothing more. Effects information is parsed since psd-tools 0.10, but applying the effects is an another (harder) task - to make it work we should emulate Photoshops' rendering features. Hopefully, it will be done eventually, but it won't happen overnight.

**Comment by robertweglarek** [comment]
Thanks for the reply @EvgenKo423
